services:
  - type: web
    name: laravel
    env: php
    buildCommand: composer install && php artisan config:cache && php artisan route:cache && php artisan view:cache
    startCommand: heroku-php-apache2 public/
    envVars:
      - key: APP_NAME
        value: NewsPortal
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        fromService:
          type: web
          name: laravel
          property: host
      - key: DB_CONNECTION
        value: mysql
