services:
  - type: web
    name: laravel-news
    plan: free
    env: php
    region: singapore
    buildCommand: composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_NAME
        value: NewsPortal
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:HiW83skc7dSUAPh7m5PP1jHcMru8QdEvyKjStpYX2wY=
      - key: DB_CONNECTION
        value: mysql
